version: '3.9'

services:
  server:
    container_name: server
    image: server
    build:
      context: ./server
      dockerfile: server.dockerfile
    platform: linux/amd64
    expose:
      - 4000 
    environment:
      - PORT=4000
      - DATABASE_URL=postgresql://postgres:123456@postgres:5432/postgres?schema=public
      - JWT_SECRET=iMyPrivateJwtSecret
      - JWT_TOKEN_EXPIRATION=1d
    depends_on:
      - postgres 

  postgres:
    container_name: db
    image: postgres:latest
    platform: linux/amd64
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=postgres
    volumes:
      - postgres:/var/lib/postgresql/data

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - 80:80 # Expose Nginx on port 80 of the host
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf # Mount the custom Nginx config
    depends_on:
      - server # Ensure Nginx starts after the server

volumes:
  postgres:
