version: '3.9'

services:
  server:
    container_name: server
    image: server
    build:
      context: ./server
      dockerfile: server.dockerfile
    platform: linux/amd64
    expose:
      - 4000
    environment:
      - PORT=4000
      - DATABASE_URL=postgresql://postgres:123456@postgres:5432/postgres?schema=public
      - JWT_SECRET=iMyPrivateJwtSecret
      - JWT_TOKEN_EXPIRATION=1d
    depends_on:
      - postgres

  postgres:
    container_name: db
    image: postgres:latest
    platform: linux/amd64
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=postgres
    volumes:
      - postgres:/var/lib/postgresql/data

  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    ports:
      - 3000:80 # Map port 80 inside the container to port 3000 on the host

volumes:
  postgres:
